// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: sgx/sgx.proto

package sgx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type NegoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xs []byte `protobuf:"bytes,1,opt,name=Xs,proto3" json:"Xs,omitempty"`
	N  []byte `protobuf:"bytes,2,opt,name=N,proto3" json:"N,omitempty"`
}

func (x *NegoRequest) Reset() {
	*x = NegoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sgx_sgx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NegoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegoRequest) ProtoMessage() {}

func (x *NegoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgx_sgx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegoRequest.ProtoReflect.Descriptor instead.
func (*NegoRequest) Descriptor() ([]byte, []int) {
	return file_sgx_sgx_proto_rawDescGZIP(), []int{0}
}

func (x *NegoRequest) GetXs() []byte {
	if x != nil {
		return x.Xs
	}
	return nil
}

func (x *NegoRequest) GetN() []byte {
	if x != nil {
		return x.N
	}
	return nil
}

// The response message containing the greetings
type NegoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hr0 []byte `protobuf:"bytes,1,opt,name=Hr0,proto3" json:"Hr0,omitempty"`
	Hr1 []byte `protobuf:"bytes,2,opt,name=Hr1,proto3" json:"Hr1,omitempty"`
}

func (x *NegoReply) Reset() {
	*x = NegoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sgx_sgx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NegoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegoReply) ProtoMessage() {}

func (x *NegoReply) ProtoReflect() protoreflect.Message {
	mi := &file_sgx_sgx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegoReply.ProtoReflect.Descriptor instead.
func (*NegoReply) Descriptor() ([]byte, []int) {
	return file_sgx_sgx_proto_rawDescGZIP(), []int{1}
}

func (x *NegoReply) GetHr0() []byte {
	if x != nil {
		return x.Hr0
	}
	return nil
}

func (x *NegoReply) GetHr1() []byte {
	if x != nil {
		return x.Hr1
	}
	return nil
}

var File_sgx_sgx_proto protoreflect.FileDescriptor

var file_sgx_sgx_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x67, 0x78, 0x2f, 0x73, 0x67, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x73, 0x67, 0x78, 0x22, 0x2b, 0x0a, 0x0b, 0x4e, 0x65, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x58, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x02, 0x58, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01,
	0x4e, 0x22, 0x2f, 0x0a, 0x09, 0x4e, 0x65, 0x67, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x48, 0x72, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x48, 0x72, 0x30,
	0x12, 0x10, 0x0a, 0x03, 0x48, 0x72, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x48,
	0x72, 0x31, 0x32, 0x38, 0x0a, 0x03, 0x50, 0x48, 0x45, 0x12, 0x31, 0x0a, 0x0b, 0x4e, 0x65, 0x67,
	0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x73, 0x67, 0x78, 0x2e, 0x4e,
	0x65, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x73, 0x67, 0x78,
	0x2e, 0x4e, 0x65, 0x67, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x73, 0x67, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sgx_sgx_proto_rawDescOnce sync.Once
	file_sgx_sgx_proto_rawDescData = file_sgx_sgx_proto_rawDesc
)

func file_sgx_sgx_proto_rawDescGZIP() []byte {
	file_sgx_sgx_proto_rawDescOnce.Do(func() {
		file_sgx_sgx_proto_rawDescData = protoimpl.X.CompressGZIP(file_sgx_sgx_proto_rawDescData)
	})
	return file_sgx_sgx_proto_rawDescData
}

var file_sgx_sgx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sgx_sgx_proto_goTypes = []interface{}{
	(*NegoRequest)(nil), // 0: sgx.NegoRequest
	(*NegoReply)(nil),   // 1: sgx.NegoReply
}
var file_sgx_sgx_proto_depIdxs = []int32{
	0, // 0: sgx.PHE.Negotiation:input_type -> sgx.NegoRequest
	1, // 1: sgx.PHE.Negotiation:output_type -> sgx.NegoReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sgx_sgx_proto_init() }
func file_sgx_sgx_proto_init() {
	if File_sgx_sgx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sgx_sgx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NegoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sgx_sgx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NegoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sgx_sgx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sgx_sgx_proto_goTypes,
		DependencyIndexes: file_sgx_sgx_proto_depIdxs,
		MessageInfos:      file_sgx_sgx_proto_msgTypes,
	}.Build()
	File_sgx_sgx_proto = out.File
	file_sgx_sgx_proto_rawDesc = nil
	file_sgx_sgx_proto_goTypes = nil
	file_sgx_sgx_proto_depIdxs = nil
}
