// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: phe/phe.proto

package phe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NegotiationBegin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xs []byte `protobuf:"bytes,1,opt,name=Xs,proto3" json:"Xs,omitempty"`
}

func (x *NegotiationBegin) Reset() {
	*x = NegotiationBegin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phe_phe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NegotiationBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiationBegin) ProtoMessage() {}

func (x *NegotiationBegin) ProtoReflect() protoreflect.Message {
	mi := &file_phe_phe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiationBegin.ProtoReflect.Descriptor instead.
func (*NegotiationBegin) Descriptor() ([]byte, []int) {
	return file_phe_phe_proto_rawDescGZIP(), []int{0}
}

func (x *NegotiationBegin) GetXs() []byte {
	if x != nil {
		return x.Xs
	}
	return nil
}

type NegotiationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X0 []byte `protobuf:"bytes,1,opt,name=X0,proto3" json:"X0,omitempty"`
}

func (x *NegotiationResponse) Reset() {
	*x = NegotiationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phe_phe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NegotiationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiationResponse) ProtoMessage() {}

func (x *NegotiationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phe_phe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiationResponse.ProtoReflect.Descriptor instead.
func (*NegotiationResponse) Descriptor() ([]byte, []int) {
	return file_phe_phe_proto_rawDescGZIP(), []int{1}
}

func (x *NegotiationResponse) GetX0() []byte {
	if x != nil {
		return x.X0
	}
	return nil
}

type T2Generation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E1 []byte `protobuf:"bytes,1,opt,name=E1,proto3" json:"E1,omitempty"`
	E2 []byte `protobuf:"bytes,2,opt,name=E2,proto3" json:"E2,omitempty"`
	E3 []byte `protobuf:"bytes,3,opt,name=E3,proto3" json:"E3,omitempty"`
}

func (x *T2Generation) Reset() {
	*x = T2Generation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phe_phe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *T2Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*T2Generation) ProtoMessage() {}

func (x *T2Generation) ProtoReflect() protoreflect.Message {
	mi := &file_phe_phe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use T2Generation.ProtoReflect.Descriptor instead.
func (*T2Generation) Descriptor() ([]byte, []int) {
	return file_phe_phe_proto_rawDescGZIP(), []int{2}
}

func (x *T2Generation) GetE1() []byte {
	if x != nil {
		return x.E1
	}
	return nil
}

func (x *T2Generation) GetE2() []byte {
	if x != nil {
		return x.E2
	}
	return nil
}

func (x *T2Generation) GetE3() []byte {
	if x != nil {
		return x.E3
	}
	return nil
}

type T2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T2 []byte `protobuf:"bytes,1,opt,name=T2,proto3" json:"T2,omitempty"`
}

func (x *T2Response) Reset() {
	*x = T2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phe_phe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *T2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*T2Response) ProtoMessage() {}

func (x *T2Response) ProtoReflect() protoreflect.Message {
	mi := &file_phe_phe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use T2Response.ProtoReflect.Descriptor instead.
func (*T2Response) Descriptor() ([]byte, []int) {
	return file_phe_phe_proto_rawDescGZIP(), []int{3}
}

func (x *T2Response) GetT2() []byte {
	if x != nil {
		return x.T2
	}
	return nil
}

type ProofOfX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag []byte `protobuf:"bytes,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	TT0  []byte `protobuf:"bytes,2,opt,name=TT0,proto3" json:"TT0,omitempty"`
}

func (x *ProofOfX) Reset() {
	*x = ProofOfX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phe_phe_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProofOfX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofOfX) ProtoMessage() {}

func (x *ProofOfX) ProtoReflect() protoreflect.Message {
	mi := &file_phe_phe_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofOfX.ProtoReflect.Descriptor instead.
func (*ProofOfX) Descriptor() ([]byte, []int) {
	return file_phe_phe_proto_rawDescGZIP(), []int{4}
}

func (x *ProofOfX) GetFlag() []byte {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *ProofOfX) GetTT0() []byte {
	if x != nil {
		return x.TT0
	}
	return nil
}

type ProverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C0   []byte `protobuf:"bytes,1,opt,name=C0,proto3" json:"C0,omitempty"`
	C1   []byte `protobuf:"bytes,2,opt,name=C1,proto3" json:"C1,omitempty"`
	U    []byte `protobuf:"bytes,3,opt,name=U,proto3" json:"U,omitempty"`
	GX1R []byte `protobuf:"bytes,4,opt,name=GX1R,proto3" json:"GX1R,omitempty"`
	X1   []byte `protobuf:"bytes,5,opt,name=X1,proto3" json:"X1,omitempty"`
}

func (x *ProverResponse) Reset() {
	*x = ProverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phe_phe_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProverResponse) ProtoMessage() {}

func (x *ProverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phe_phe_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProverResponse.ProtoReflect.Descriptor instead.
func (*ProverResponse) Descriptor() ([]byte, []int) {
	return file_phe_phe_proto_rawDescGZIP(), []int{5}
}

func (x *ProverResponse) GetC0() []byte {
	if x != nil {
		return x.C0
	}
	return nil
}

func (x *ProverResponse) GetC1() []byte {
	if x != nil {
		return x.C1
	}
	return nil
}

func (x *ProverResponse) GetU() []byte {
	if x != nil {
		return x.U
	}
	return nil
}

func (x *ProverResponse) GetGX1R() []byte {
	if x != nil {
		return x.GX1R
	}
	return nil
}

func (x *ProverResponse) GetX1() []byte {
	if x != nil {
		return x.X1
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gr []byte `protobuf:"bytes,1,opt,name=Gr,proto3" json:"Gr,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phe_phe_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phe_phe_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_phe_phe_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetGr() []byte {
	if x != nil {
		return x.Gr
	}
	return nil
}

type UpdateToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delta0 []byte `protobuf:"bytes,1,opt,name=Delta0,proto3" json:"Delta0,omitempty"`
	Delta1 []byte `protobuf:"bytes,2,opt,name=Delta1,proto3" json:"Delta1,omitempty"`
}

func (x *UpdateToken) Reset() {
	*x = UpdateToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phe_phe_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToken) ProtoMessage() {}

func (x *UpdateToken) ProtoReflect() protoreflect.Message {
	mi := &file_phe_phe_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToken.ProtoReflect.Descriptor instead.
func (*UpdateToken) Descriptor() ([]byte, []int) {
	return file_phe_phe_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateToken) GetDelta0() []byte {
	if x != nil {
		return x.Delta0
	}
	return nil
}

func (x *UpdateToken) GetDelta1() []byte {
	if x != nil {
		return x.Delta1
	}
	return nil
}

var File_phe_phe_proto protoreflect.FileDescriptor

var file_phe_phe_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x68, 0x65, 0x2f, 0x70, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x70, 0x68, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x58, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x58, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x4e, 0x65, 0x67, 0x6f,
	0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x58, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x58, 0x30, 0x22,
	0x3e, 0x0a, 0x0c, 0x54, 0x32, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x45, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x45, 0x31, 0x12,
	0x0e, 0x0a, 0x02, 0x45, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x45, 0x32, 0x12,
	0x0e, 0x0a, 0x02, 0x45, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x45, 0x33, 0x22,
	0x1c, 0x0a, 0x0a, 0x54, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x54, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x54, 0x32, 0x22, 0x30, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x4f, 0x66, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x54, 0x54, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x54, 0x54, 0x30, 0x22,
	0x62, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x43, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x43,
	0x30, 0x12, 0x0e, 0x0a, 0x02, 0x43, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x43,
	0x31, 0x12, 0x0c, 0x0a, 0x01, 0x55, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x55, 0x12,
	0x12, 0x0a, 0x04, 0x47, 0x58, 0x31, 0x52, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x47,
	0x58, 0x31, 0x52, 0x12, 0x0e, 0x0a, 0x02, 0x58, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x02, 0x58, 0x31, 0x22, 0x1f, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x47, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x47, 0x72, 0x22, 0x3d, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x30, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x30, 0x12, 0x16, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x74, 0x61, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x44, 0x65, 0x6c,
	0x74, 0x61, 0x31, 0x32, 0xee, 0x01, 0x0a, 0x0a, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x47,
	0x65, 0x6e, 0x12, 0x40, 0x0a, 0x0b, 0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x15, 0x2e, 0x70, 0x68, 0x65, 0x2e, 0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x1a, 0x18, 0x2e, 0x70, 0x68, 0x65, 0x2e, 0x4e,
	0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x13, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72,
	0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x2e, 0x70, 0x68,
	0x65, 0x2e, 0x54, 0x32, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0f,
	0x2e, 0x70, 0x68, 0x65, 0x2e, 0x54, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x2f, 0x0a, 0x07, 0x5a, 0x4b, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x0d, 0x2e, 0x70,
	0x68, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x4f, 0x66, 0x58, 0x1a, 0x13, 0x2e, 0x70, 0x68,
	0x65, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x30, 0x0a, 0x06, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x70,
	0x68, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x70, 0x68, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2e, 0x2f, 0x70, 0x68, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phe_phe_proto_rawDescOnce sync.Once
	file_phe_phe_proto_rawDescData = file_phe_phe_proto_rawDesc
)

func file_phe_phe_proto_rawDescGZIP() []byte {
	file_phe_phe_proto_rawDescOnce.Do(func() {
		file_phe_phe_proto_rawDescData = protoimpl.X.CompressGZIP(file_phe_phe_proto_rawDescData)
	})
	return file_phe_phe_proto_rawDescData
}

var file_phe_phe_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_phe_phe_proto_goTypes = []interface{}{
	(*NegotiationBegin)(nil),    // 0: phe.NegotiationBegin
	(*NegotiationResponse)(nil), // 1: phe.NegotiationResponse
	(*T2Generation)(nil),        // 2: phe.T2Generation
	(*T2Response)(nil),          // 3: phe.T2Response
	(*ProofOfX)(nil),            // 4: phe.ProofOfX
	(*ProverResponse)(nil),      // 5: phe.ProverResponse
	(*UpdateRequest)(nil),       // 6: phe.UpdateRequest
	(*UpdateToken)(nil),         // 7: phe.UpdateToken
}
var file_phe_phe_proto_depIdxs = []int32{
	0, // 0: phe.KeyPairGen.Negotiation:input_type -> phe.NegotiationBegin
	2, // 1: phe.KeyPairGen.ThirdPartGeneration:input_type -> phe.T2Generation
	4, // 2: phe.KeyPairGen.ZKProof:input_type -> phe.ProofOfX
	6, // 3: phe.KeyPairGen.Rotate:input_type -> phe.UpdateRequest
	1, // 4: phe.KeyPairGen.Negotiation:output_type -> phe.NegotiationResponse
	3, // 5: phe.KeyPairGen.ThirdPartGeneration:output_type -> phe.T2Response
	5, // 6: phe.KeyPairGen.ZKProof:output_type -> phe.ProverResponse
	7, // 7: phe.KeyPairGen.Rotate:output_type -> phe.UpdateToken
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_phe_phe_proto_init() }
func file_phe_phe_proto_init() {
	if File_phe_phe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phe_phe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NegotiationBegin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phe_phe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NegotiationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phe_phe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*T2Generation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phe_phe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*T2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phe_phe_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProofOfX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phe_phe_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phe_phe_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phe_phe_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phe_phe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phe_phe_proto_goTypes,
		DependencyIndexes: file_phe_phe_proto_depIdxs,
		MessageInfos:      file_phe_phe_proto_msgTypes,
	}.Build()
	File_phe_phe_proto = out.File
	file_phe_phe_proto_rawDesc = nil
	file_phe_phe_proto_goTypes = nil
	file_phe_phe_proto_depIdxs = nil
}
